services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    hostname: "postgres"
    user: "root"
    ports:
      - "5432:5432"
    environment:
      ACCEPT_EULA: "Y"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "dba_password123#"
    volumes:
      - type: "bind"
        source: "~/.postgres-docker"
        target: "/var/lib/postgresql"
